SELECT *
WHERE { 
   ?dataset_uri qb:structure/qb:component ?unitUri .
   ?unitUri qb:attribute <http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure> 
	OPTIONAL { 
        ?unitUri rdfs:label ?unitLabel.
    } 
}