PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX csvw: <http://www.w3.org/ns/csvw#>
PREFIX om2: <http://www.ontology-of-units-of-measure.org/resource/om-2/>
PREFIX qudt: <http://qudt.org/schema/qudt/>

SELECT DISTINCT ?unit ?unitLabel
WHERE {   
    ?unit a ?unitType.
    FILTER(?unitType IN (qudt:Unit, om2:Unit)).

    ?unit rdfs:label ?unitLabel.
}    