PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX csvw: <http://www.w3.org/ns/csvw#>

SELECT ?csvUrl ?columnName ?columnTitle
WHERE {
    ?table csvw:tableSchema/csvw:column/rdf:rest*/rdf:first ?column;
           csvw:url ?csvUrl.
        
    OPTIONAL{
        ?column csvw:title ?columnTitle.
    }
    OPTIONAL{
        ?column csvw:name ?columnName.
    }
}