PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX csvw: <http://www.w3.org/ns/csvw#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT DISTINCT ?tablePrimaryKey
WHERE {   

    ?table csvw:tableSchema ?tableSchema;
           csvw:url ?tableUrl.
           
    ?tableSchema csvw:primaryKey ?tablePrimaryKey.

    BIND (?table_url as ?tableUrlStr).

    FILTER (strends(str(?tableUrl), ?tableUrlStr)).
}