PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX csvw: <http://www.w3.org/ns/csvw#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?csvUrl ?tableAboutUrl (GROUP_CONCAT(?tablePrimaryKey ; separator='|') AS ?tablePrimaryKeys)
WHERE {
    [] csvw:tableSchema ?tableSchema;
       csvw:url ?csvUrl.

    ?tableSchema csvw:aboutUrl ?tableAboutUrl;
                 csvw:primaryKey ?tablePrimaryKey.
}
GROUP BY ?csvUrl ?tableAboutUrl
