PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX csvw: <http://www.w3.org/ns/csvw#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?tableSchema
WHERE {
    [] csvw:tableSchema ?tableSchema.
    FILTER (isIRI(?tableSchema) = false).
}