PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?resourceValUri ?resourceLabel
WHERE {
    ?resourceValUri rdfs:label ?resourceLabel;
                    a rdfs:Resource.
}

# ValuesBinding(
    # variable_names=["attrValUri"],
    # rows=[
    #     [URIRef("http://example.com/uri1")],
    #     [URIRef("http://example.com/uri2")]
    # ]
# )
