pipeline {
    agent {
        dockerfile { 
            dir 'external-docs'
            args '-u root'
            reuseNode true
        }
    }
    stages {
        stage('Documentation') {
            steps {
                script {
                        dir ('external-docs'){
                            sh 'bundle install'
                            // Unfortunately, the alphagov/tech-docs-template isn't very flexible when it comes to URLs, so we need to tell it exactly
                            // where on the server it lives so it can get all of its URLs in order.
                            // This does mean that what we build here isn't portable & if we deploy it anywhere, we'll need to alter this `HTTP_PREFIX`.
                            String buildUrl = "${BUILD_URL}artifact/external-docs/build/"
                            // Get rid of the host information, because apparently middleman can't handle that.
                            buildUrl = buildUrl.replace(JENKINS_URL, "/")

                            sh "HTTP_PREFIX='${buildUrl}' bundle exec middleman build"
                        }
                        stash name: 'docs', includes: 'external-docs/build/**/*'
                }
            }
        }
    }
     post {
        always {
            script {
                try {
                    unstash name: 'docs'
                } catch (Exception e) {
                    echo 'docs stash does not exist'
                }

                archiveArtifacts artifacts: 'external-docs/build/**/*', fingerprint: true

                // Set more permissive permissions on all files so future processes/Jenkins can easily delete them.
                sh 'chmod -R ugo+rw .'
                // Clean up any unwanted files lying about.
                sh "git clean -fxd"
            }
        }
    }
}