pipeline{
    agent any
    stages{
        stage('Setup'){
            steps{
                script{
                    echo "External documentation work in progress"
                    sh "pwd"
                    sh "ls -la"
                }
            }
        }
    }
}