# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, "..")


# -- Project information -----------------------------------------------------

project = "csvwlib-csvqb"
copyright = "2021, Office for National Statistics"
author = "Office for National Statistics"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.todo",
    "sphinx.ext.intersphinx",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]


intersphinx_mapping = {
    "python": ("https://docs.python.org/3.9", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/dev", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "rdflib": ("https://rdflib.readthedocs.io/en/stable/", None),
    "sharedmodels": (
        "../../../../sharedmodels/docs/_build/html/",
        "../../sharedmodels/docs/_build/html/objects.inv",
    ),
}

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_book_theme"

autodoc_default_options = {
    "members": True,
    "member-order": "groupwise",
    "private-members": False,
    "inherited-members": True,
    "show-inheritance": True,
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__,__dict__,__module__,__slots__,_abc_impl,__abstractmethods__,__annotations__,__orig_bases__,__parameters__,_is_protocol,__init_subclass__,__class_getitem__",
}
